inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.3
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Appraisals'
  Exclude:
    - 'spec/dummy/**/*'
    - 'lib/generators/**/*'

Layout/LineLength:
  Max: 150


Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
